### ISSUE TITLE
Matchers types are missing with .not

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/expect-webdriverio#171]
### Environment

**`expect-webdriverio` version**: 1.3.0
**WebdriverIO version**: 6.4.1
**Test Framework**: mocha (jest/jasmine/mocha/cucumber/etc)
**async/sync**: sync (is `@wdio/sync` used? - Yes)

### Description
1. `expect(section).not.toHaveClass('page2')`

`Property 'toHaveClass' does not exist on type 'Matchers<Element>'`

### Additional Information

Looks like a regression since https://github.com/webdriverio/expect-webdriverio/pull/122

**Comment by mgrybyk** [comment]
should be fixed with the PR
