### PR TITLE
fix .not types

### LINKED ISSUE #171: Matchers types are missing with .not
### Environment

**`expect-webdriverio` version**: 1.3.0
**WebdriverIO version**: 6.4.1
**Test Framework**: mocha (jest/jasmine/mocha/cucumber/etc)
**async/sync**: sync (is `@wdio/sync` used? - Yes)

### Description
1. `expect(section).not.toHaveClass('page2')`

`Property 'toHaveClass' does not exist on type 'Matchers<Element>'`

### Additional Information

Looks like a regression since https://github.com/webdriverio/expect-webdriverio/pull/122

### PR DESCRIPTION
**Pull request by mgrybyk**
Fix types for `.not` matchers like `expect(section).not.toHaveClass('page2')`

fixes #171

### CODE REVIEW

**Comment by mgrybyk** [comment]
CI failing due to https://github.com/webdriverio/expect-webdriverio/issues/169

**Review by christian-bromann — APPROVED** [review]
👍
